@if(empty($user->substantiated_at))<option selected disabled hidden class="hidden"></option>@endif
<option value="AL" @if(old('state', isset($user->state) ? $user->state : '')=="AL")selected @endif>AL</option>
<option value="AK" @if(old('state', isset($user->state) ? $user->state : '')=="AK")selected @endif>AK</option>
<option value="AZ" @if(old('state', isset($user->state) ? $user->state : '')=="AZ")selected @endif>AZ</option>
<option value="AR" @if(old('state', isset($user->state) ? $user->state : '')=="AR")selected @endif>AR</option>
<option value="CA" @if(old('state', isset($user->state) ? $user->state : '')=="CA")selected @endif>CA</option>
<option value="CO" @if(old('state', isset($user->state) ? $user->state : '')=="CO")selected @endif>CO</option>
<option value="CT" @if(old('state', isset($user->state) ? $user->state : '')=="CT")selected @endif>CT</option>
<option value="DE" @if(old('state', isset($user->state) ? $user->state : '')=="DE")selected @endif>DE</option>
<option value="DC" @if(old('state', isset($user->state) ? $user->state : '')=="DC")selected @endif>DC</option>
<option value="FL" @if(old('state', isset($user->state) ? $user->state : '')=="FL")selected @endif>FL</option>
<option value="GA" @if(old('state', isset($user->state) ? $user->state : '')=="GA")selected @endif>GA</option>
<option value="HI" @if(old('state', isset($user->state) ? $user->state : '')=="HI")selected @endif>HI</option>
<option value="ID" @if(old('state', isset($user->state) ? $user->state : '')=="ID")selected @endif>ID</option>
<option value="IL" @if(old('state', isset($user->state) ? $user->state : '')=="IL")selected @endif>IL</option>
<option value="IN" @if(old('state', isset($user->state) ? $user->state : '')=="IN")selected @endif>IN</option>
<option value="IA" @if(old('state', isset($user->state) ? $user->state : '')=="IA")selected @endif>IA</option>
<option value="KS" @if(old('state', isset($user->state) ? $user->state : '')=="KS")selected @endif>KS</option>
<option value="KY" @if(old('state', isset($user->state) ? $user->state : '')=="KY")selected @endif>KY</option>
<option value="LA" @if(old('state', isset($user->state) ? $user->state : '')=="LA")selected @endif>LA</option>
<option value="ME" @if(old('state', isset($user->state) ? $user->state : '')=="ME")selected @endif>ME</option>
<option value="MD" @if(old('state', isset($user->state) ? $user->state : '')=="MD")selected @endif>MD</option>
<option value="MA" @if(old('state', isset($user->state) ? $user->state : '')=="MA")selected @endif>MA</option>
<option value="MI" @if(old('state', isset($user->state) ? $user->state : '')=="MI")selected @endif>MI</option>
<option value="MN" @if(old('state', isset($user->state) ? $user->state : '')=="MN")selected @endif>MN</option>
<option value="MS" @if(old('state', isset($user->state) ? $user->state : '')=="MS")selected @endif>MS</option>
<option value="MO" @if(old('state', isset($user->state) ? $user->state : '')=="MO")selected @endif>MO</option>
<option value="MT" @if(old('state', isset($user->state) ? $user->state : '')=="MT")selected @endif>MT</option>
<option value="NE" @if(old('state', isset($user->state) ? $user->state : '')=="NE")selected @endif>NE</option>
<option value="NV" @if(old('state', isset($user->state) ? $user->state : '')=="NV")selected @endif>NV</option>
<option value="NH" @if(old('state', isset($user->state) ? $user->state : '')=="NH")selected @endif>NH</option>
<option value="NJ" @if(old('state', isset($user->state) ? $user->state : '')=="NJ")selected @endif>NJ</option>
<option value="NM" @if(old('state', isset($user->state) ? $user->state : '')=="NM")selected @endif>NM</option>
<option value="NY" @if(old('state', isset($user->state) ? $user->state : '')=="NY")selected @endif>NY</option>
<option value="NC" @if(old('state', isset($user->state) ? $user->state : '')=="NC")selected @endif>NC</option>
<option value="ND" @if(old('state', isset($user->state) ? $user->state : '')=="ND")selected @endif>ND</option>
<option value="OH" @if(old('state', isset($user->state) ? $user->state : '')=="OH")selected @endif>OH</option>
<option value="OK" @if(old('state', isset($user->state) ? $user->state : '')=="OK")selected @endif>OK</option>
<option value="OR" @if(old('state', isset($user->state) ? $user->state : '')=="OR")selected @endif>OR</option>
<option value="PA" @if(old('state', isset($user->state) ? $user->state : '')=="PA")selected @endif>PA</option>
<option value="RI" @if(old('state', isset($user->state) ? $user->state : '')=="RI")selected @endif>RI</option>
<option value="SC" @if(old('state', isset($user->state) ? $user->state : '')=="SC")selected @endif>SC</option>
<option value="SD" @if(old('state', isset($user->state) ? $user->state : '')=="SD")selected @endif>SD</option>
<option value="TN" @if(old('state', isset($user->state) ? $user->state : '')=="TN")selected @endif>TN</option>
<option value="TX" @if(old('state', isset($user->state) ? $user->state : '')=="TX")selected @endif>TX</option>
<option value="UT" @if(old('state', isset($user->state) ? $user->state : '')=="UT")selected @endif>UT</option>
<option value="VT" @if(old('state', isset($user->state) ? $user->state : '')=="VT")selected @endif>VT</option>
<option value="VA" @if(old('state', isset($user->state) ? $user->state : '')=="VA")selected @endif>VA</option>
<option value="WA" @if(old('state', isset($user->state) ? $user->state : '')=="WA")selected @endif>WA</option>
<option value="WV" @if(old('state', isset($user->state) ? $user->state : '')=="WV")selected @endif>WV</option>
<option value="WI" @if(old('state', isset($user->state) ? $user->state : '')=="WI")selected @endif>WI</option>
<option value="WY" @if(old('state', isset($user->state) ? $user->state : '')=="WY")selected @endif>WY</option>